
site_name: Odak
site_description: The fundamental library for scientific computing in optical and visual perception sciences.
site_author: Kaan Akşit
site_url: 'https://kaanaksit.github.io/odak/'

repo_name: kunguz/odak
repo_url: 'https://github.com/kaanaksit/odak'

copyright: 'Copyright &copy; 2022'

nav:
  - Getting started: 'index.md'
  - Contributing: 'contributing.md'
  - Computer-Generated Holography:
    - Introduction: 'cgh.md'
    - odak.wave: 'odak/wave.md'
    - odak.learn.wave: 'odak/learn_wave.md'
  - General toolkit:
    - Introduction: 'toolkit.md'
    - odak.tools: 'odak/tools.md'
    - odak.learn.tools: 'odak/learn_tools.md'
  - Machine learning:
    - Introduction: 'machine_learning.md'
    - odak.fit: 'odak/fit.md'
    - odak.learn.models : 'odak/learn_models.md'
  - Raytracing:
    - Introduction: 'raytracing.md'
    - odak.raytracing: 'odak/raytracing.md'
    - odak.learn.raytracing: 'odak/learn_raytracing.md'
  - Visual perception:
    - Introduction: 'perception.md'
    - odak.learn.perception: 'odak/learn_perception.md'

theme:
    name: material
    custom_dir: overrides
    theme:
        features:
            - navigation.instant
            - navigation.tabs
    palette:
        primary: black
    highlightjs: true
    hljs_languages:
        - python

plugins:
   - search
   - mkdocstrings
   - autorefs
markdown_extensions:
   - toc:
       permalink: true
   - admonition
   - pymdownx.superfences
   - pymdownx.details
   - pymdownx.arithmatex:
       generic: true
   - pymdownx.emoji:
       emoji_index: !!python/name:materialx.emoji.twemoji
       emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
   - 'javascripts/config.js'
   - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
   - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/kaanaksit
