
site_name: Odak
site_description: The fundamental library for scientific computing in optical and visual perception sciences.
site_author: Kaan Akşit
site_url: 'https://kunguz.github.io/odak/'

repo_name: kunguz/odak
repo_url: 'https://github.com/kunguz/odak'

copyright: 'Copyright &copy; 2021'

nav:
  - Getting started: 'index.md'
  - Computer-Generated Holography: 'cgh.md'

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python

plugins:
    - search
