
site_name: Odak
site_description: The fundamental library for scientific computing in optical and visual perception sciences.
site_author: Kaan Akşit
site_url: 'https://kunguz.github.io/odak/'

repo_name: kunguz/odak
repo_url: 'https://github.com/kunguz/odak'

copyright: 'Copyright &copy; 2021'

nav:
  - Getting started: 'index.md'
  - Computer-Generated Holography: 'cgh.md'
  - Visual perception: 'perception.md'

theme:
    name: material
    theme:
        features:
            - navigation.instant
            - navigation.tabs
    palette:
        primary: red
    highlightjs: true
    hljs_languages:
        - python

plugins:
   - search
markdown_extensions:
   - pymdownx.arithmatex:
       generic: true
extra_javascript:
   - 'javascripts/config.js'
   - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
   - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
