
site_name: Odak
site_description: The fundamental library for scientific computing in optical and visual perception sciences.
site_author: Kaan Akşit
site_url: 'https://kunguz.github.io/odak/'

repo_name: kunguz/odak
repo_url: 'https://github.com/kunguz/odak'

copyright: 'Copyright &copy; 2021'

nav:
  - Main: 'index.md'
  - For users:
      - What is Odak?: 'beginning.md'
      - Installation: 'installation.md'
  - Additional information:
      - Odak on GitHub: 'https://github.com/kunguz/odak'
      - License of Odak: 'https://github.com/kunguz/odak/blob/master/LICENSE.txt'

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python

plugins:
    - search
