title: Odak
description: The fundamental library for scientific computing in optical and visual perception sciences.
remote_theme: carlosperate/jekyll-theme-rtd

site_author: Kaan Akşit
repo_url: "https://github.com/kunguz/odak"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
