name: ci 
on:
  push:
    branches: 
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
      - run: pip install --upgrade pip
      - run: pip install torch
      - run: pip install numpy
      - run: pip install plyfile
      - run: pip install Pillow
      - run: pip install tqdm
      - run: pip install jinja2
      - run: pip install mkdocstrings
      - run: pip install mkdocs-material
      - run: pip install pytkdocs[numpy-style]
      - run: pip install mkdocstrings-python
      - run: mkdocs gh-deploy --force

